# Homework 3 - NumPy

### NAME: Holly Cheek 
### STUDENT ID: 3033094443

In [1]:
# Do not delete this cell.
import numpy as np

### Since we will run autograder on your notebook, for each question please do not reuse variable names that have been used in previous questions.

## NumPy Introduction

__1a) Create two numpy arrays called a and b where a should be all integers between 25-34 (inclusive), and b should be ten evenly spaced numbers between 1-6 (inclusive). Print a and b.__

In [2]:
a = np.arange(25,35)
b = np.linspace(1,6, num = 10)
print(a)
print(b)

[25 26 27 28 29 30 31 32 33 34]
[1.         1.55555556 2.11111111 2.66666667 3.22222222 3.77777778
 4.33333333 4.88888889 5.44444444 6.        ]


__1b) Cube (i.e. raise to the power of 3) all the elements in both a and b (element-wise). Store the results in two new arrays called cubed_a and cubed_b. Print cubed_a and cubed_b.__

In [3]:
cubed_a = np.power(a, 3)
cubed_b = np.power(b, 3)
print(cubed_a)
print(cubed_b)

[15625 17576 19683 21952 24389 27000 29791 32768 35937 39304]
[  1.           3.76406036   9.40877915  18.96296296  33.45541838
  53.91495199  81.37037037 116.85048011 161.38408779 216.        ]


__1c) Add the two cubed arrays (e.g., [1,2] + [3,4] = [4,6]) and store the result in an array called c. Print c.__

In [4]:
c = np.add(cubed_a, cubed_b)
print(c)

[15626.         17579.76406036 19692.40877915 21970.96296296
 24422.45541838 27053.91495199 29872.37037037 32884.85048011
 36098.38408779 39520.        ]


__1d) Sum the elements with even indices of c and store the result in a variable called d. Print d.__

In [5]:
d = sum(c[::2])
print(d)

125711.61865569273


__1e) Take the element-wise square root of the c and store the result in an array called e. Print e.__

In [6]:
e = np.sqrt(c)
print(e)

[125.00399994 132.58870261 140.32964327 148.22605359 156.27685503
 164.48074341 172.83625306 181.34180566 189.99574755 198.79637824]


__1f) Append b to a, reshape the appended array so that it is a 4x5, 2d array and store the results in a variable called m. Print m.__


In [7]:
m = np.concatenate((a,b)).reshape((4,5))
print(m)

[[25.         26.         27.         28.         29.        ]
 [30.         31.         32.         33.         34.        ]
 [ 1.          1.55555556  2.11111111  2.66666667  3.22222222]
 [ 3.77777778  4.33333333  4.88888889  5.44444444  6.        ]]


__1g) Extract the third and the fourth column of the m matrix. Store the resulting 4x2 matrix in a new variable called m2. Print m2.__


In [8]:
m2 = m[:,2:4]
print(m2)

[[27.         28.        ]
 [32.         33.        ]
 [ 2.11111111  2.66666667]
 [ 4.88888889  5.44444444]]


__1h) Take the dot product of m and m2. Store the results in a matrix called m3. Print m3.
Note that Dot product of two matrices A$\cdot$B =A<sup>T</sup>B__

In [9]:
m3 = m2.T.dot(m)
print(m3)

[[1655.58024691 1718.4691358  1781.35802469 1844.24691358 1907.13580247]
 [1713.2345679  1778.74074074 1844.24691358 1909.75308642 1975.25925926]]


__1i) Round the m3 matrix to three decimal points. Store the result in m4. Print m4.__


In [10]:
m4 = np.round(m3, decimals =3)
print(m4)

[[1655.58  1718.469 1781.358 1844.247 1907.136]
 [1713.235 1778.741 1844.247 1909.753 1975.259]]


## NumPy and Masks
__2a) Create an array called f where the values are cosine(x) for x from 0 to pi with 50 equally spaced values (inclusive). Print f.__

In [11]:
f = np.cos(np.linspace(0, np.pi, num = 50))
print(f)

[ 1.          0.99794539  0.99179001  0.98155916  0.96729486  0.94905575
  0.92691676  0.90096887  0.8713187   0.8380881   0.80141362  0.76144596
  0.71834935  0.67230089  0.6234898   0.57211666  0.51839257  0.46253829
  0.40478334  0.34536505  0.28452759  0.22252093  0.1595999   0.09602303
  0.03205158 -0.03205158 -0.09602303 -0.1595999  -0.22252093 -0.28452759
 -0.34536505 -0.40478334 -0.46253829 -0.51839257 -0.57211666 -0.6234898
 -0.67230089 -0.71834935 -0.76144596 -0.80141362 -0.8380881  -0.8713187
 -0.90096887 -0.92691676 -0.94905575 -0.96729486 -0.98155916 -0.99179001
 -0.99794539 -1.        ]


__2b) Use a 'mask' to get an array that is True when f >= 1/2 and False when f < 1/2. Store the result in an array called g. Print g.__

In [12]:
g = f >= 1/2
print(g)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False]


__2c) Create an array called h that has only those values where f>= 1/2. Print h.__

In [13]:
h = f[g]
print(h)

[1.         0.99794539 0.99179001 0.98155916 0.96729486 0.94905575
 0.92691676 0.90096887 0.8713187  0.8380881  0.80141362 0.76144596
 0.71834935 0.67230089 0.6234898  0.57211666 0.51839257]


## NumPy and 2 Variable Prediction

__Let 'x' be the number of miles a person drives per day and 'y' be the dollars spent on buying car fuel (per day).__
  
__We have created 2 numpy arrays each of size 100 that represent x and y.  
x (number of miles) ranges from 1 to 10 with a uniform noise of (0,1/2)  
y (money spent in dollars) will be from 1 to 20 with a uniform noise (0,1)__ 


In [14]:
# seed the random number generator with a fixed value
# Do not delete this cell
np.random.seed(500)

x=np.linspace(1,10,100)+ np.random.uniform(low=0,high=.5,size=100) 
y=np.linspace(1,20,100)+ np.random.uniform(low=0,high=1,size=100)
print ('x = ', x)
print ('y = ', y)

x =  [ 1.34683976  1.12176759  1.51512398  1.55233174  1.40619168  1.65075498
  1.79399331  1.80243817  1.89844195  2.00100023  2.3344038   2.22424872
  2.24914511  2.36268477  2.49808849  2.8212704   2.68452475  2.68229427
  3.09511169  2.95703884  3.09047742  3.2544361   3.41541904  3.40886375
  3.50672677  3.74960644  3.64861355  3.7721462   3.56368566  4.01092701
  4.15630694  4.06088549  4.02517179  4.25169402  4.15897504  4.26835333
  4.32520644  4.48563164  4.78490721  4.84614839  4.96698768  5.18754259
  5.29582013  5.32097781  5.0674106   5.47601124  5.46852704  5.64537452
  5.49642807  5.89755027  5.68548923  5.76276141  5.94613234  6.18135713
  5.96522091  6.0275473   6.54290191  6.4991329   6.74003765  6.81809807
  6.50611821  6.91538752  7.01250925  6.89905417  7.31314433  7.20472297
  7.1043621   7.48199528  7.58957227  7.61744354  7.6991707   7.85436822
  8.03510784  7.80787781  8.22410224  7.99366248  8.40581097  8.28913792
  8.45971515  8.54227144  8.6906456   8.618565

__3a) Find Expected value of x and the expected value of y. Store the results in two variables called ex and ey.__

In [21]:
ex = np.mean(x)
ey = np.mean(y)
print(ex, ey)

5.782532541587923 11.012981683344968


__3b) Find variance of distributions of x and y. Store the results in two variables called varx and vary.__

In [22]:
varx = np.var(x)
vary = np.var(y)
print(varx, vary)

7.03332752947585 30.113903575509635


__3c) Find co-variance of x and y. Store the result in a variable called cov.__

In [23]:
cov = np.mean(x*y) - ex * ey
print(cov)
print(np.cov(x,y)) #only the diagonal elements

14.511166394475424
[[ 7.10437124 14.65774383]
 [14.65774383 30.41808442]]


__3d) Assuming that number of dollars spent in car fuel is only dependant on the miles driven, by  a linear relationship.  
Write code that uses a linear predictor to calculate a predicted value of y for each x
i.e. y_predicted = f(x) = y0 + kx. Store your predicitions in an array called y_pred. Print y_pred.__  

In [24]:
def predictor(x_val):
    slope = cov/varx
    y_int = ey - slope*ex
    return (y_int + slope * x_val)

y_pred = predictor(x)
print(y_pred)

[ 1.86125717  1.39688809  2.20846128  2.28522836  1.98371207  2.48829527
  2.78382468  2.80124813  2.9993232   3.21092152  3.8988      3.67152796
  3.7228942   3.9571493   4.23651436  4.9033035   4.62116978  4.61656787
  5.46829307  5.18342105  5.45873164  5.79701128  6.12915141  6.11562653
  6.31753758  6.81864709  6.61027849  6.86515115  6.43505522  7.35780389
  7.65775187  7.46087825  7.38719373  7.85455455  7.66325667  7.88892606
  8.00622544  8.33721481  8.95468038  9.08103323  9.33034895  9.78539799
 10.00879629 10.06070164  9.53754157 10.38056671 10.36512531 10.72999716
 10.42269073 11.25028634 10.81276185 10.97218988 11.35052091 11.83583685
 11.38990445 11.51849632 12.58177632 12.49147206 12.98850691 13.14956122
 12.50588416 13.35028889 13.5506705  13.31658991 14.17094102 13.947246
 13.74018137 14.51931443 14.74126735 14.79877137 14.96739089 15.28759454
 15.66049665 15.1916755  16.05043004 15.57498655 16.42533161 16.18461169
 16.53654675 16.70687695 17.01300263 16.86428603 17.3

__3e) Put the prediction error into an array called y_error. Print y_error.__

In [27]:
y_error = np.power(y_pred - y, 2) #standard error
print(y_error)

[3.91074238e-02 3.90089068e-01 1.00602426e-02 6.28174407e-04
 4.34159397e-04 2.18246155e-01 6.00221492e-02 2.85588517e-01
 5.98611651e-02 4.58341762e-02 2.52102923e-01 7.71452229e-02
 3.86128331e-03 1.81289615e-01 8.67161417e-03 7.46587776e-01
 1.33978081e-02 9.95931872e-02 3.92702968e-01 1.61331949e-01
 2.12589019e-01 2.29961598e-01 1.30107881e-01 3.18226480e-02
 3.47417298e-01 1.18615933e-02 5.06305934e-03 8.42879328e-02
 5.51040190e-01 3.64155664e-02 1.26407037e-01 1.97742526e-02
 1.54484457e-01 3.22386643e-03 3.76118518e-01 6.44980460e-01
 6.02134420e-01 1.48256557e-02 4.06192410e-03 6.96083892e-02
 2.10937426e-01 1.52454276e-02 3.68125897e-01 4.03181563e-02
 4.36342204e-03 9.40673772e-02 1.09345421e-01 3.94107735e-03
 5.77405634e-01 4.56932708e-01 4.28612855e-01 7.95280194e-04
 7.40775594e-03 6.84928710e-02 5.32864845e-01 3.63682187e-01
 1.64543313e-01 2.91277455e-03 4.25053049e-04 8.15041286e-02
 5.48376537e-01 3.47024722e-01 1.87870128e-01 5.80371345e-01
 7.43982492e-04 1.060440

__3f) Write code that calculates the root mean square error (RMSE), that is root of average of y_error squared. Store the result in a variable called rmse. Print rmse.__

In [32]:
rmse = np.sqrt(np.mean(y_error))
print(rmse)

0.41767772366856115


## Congratulations on completing hw3! Don't forget to click Kernel -> Restart & Run All, and submit this notebook on Gradescope.